version: "2.2"

services:

# FLINK ----------------------------------------------------------------------------------------------------------------

  jobmanager:
    image: flink:latest
    container_name: jobmanager
    ports:
      - "8081:8081" # Web ui port
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        metrics.reporter.influxdb.factory.class: org.apache.flink.metrics.influxdb.InfluxdbReporterFactory
        metrics.reporter.influxdb.scheme: http
        metrics.reporter.influxdb.host: influxdb
        metrics.reporter.influxdb.port: 8086
        metrics.reporter.influxdb.db: flink
        metrics.reporter.influxdb.username: metrics
        metrics.reporter.influxdb.password: metrics123
        metrics.reporter.influxdb.retentionPolicy: one_hour
        metrics.reporter.influxdb.consistency: ANY
        metrics.reporter.influxdb.connectTimeout: 60000
        metrics.reporter.influxdb.writeTimeout: 60000
        metrics.reporter.influxdb.interval: 60 SECONDS
    volumes:
      - ./target:/opt/flink/queries/

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2


# NIFI -----------------------------------------------------------------------------------------------------------------

  nifi:
    image: apache/nifi
    container_name: nifi
    ports:
      - '9090:8080' # Web ui port
    volumes:
      - ./nifi:/nifi-conf/
      - nifi_volume:/opt/nifi/nifi-current/conf/

# INFLUXDB -------------------------------------------------------------------------------------------------------------

  #influxdb:
    #image: influxdb:2.0
    #container_name: influxdb
    #ports:
    #  - '8086:8086' # Web ui Port
    #environment:
    #  - DOCKER_INFLUXDB_INIT_MODE=setup
    #  - DOCKER_INFLUXDB_INIT_USERNAME=admin
    #  - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
    #  - DOCKER_INFLUXDB_INIT_ORG=my_org
    #  - DOCKER_INFLUXDB_INIT_BUCKET=my_bucket
    #  - V1_DB_NAME=flink
    #  - V1_RP_NAME=one_hour
    #  - V1_AUTH_USERNAME=metrics
    #  - V1_AUTH_PASSWORD=metrics123
    #volumes:
    #  - ./influxdb/scripts:/docker-entrypoint-initdb.d

# GRAPHITE -------------------------------------------------------------------------------------------------------------

  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    ports:
      - '80:80'
      - "8080:8080"
      - "2003:2003"
      - "2004:2004"
      - "8125:8125/udp"
      - "8126:8126"

# REDIS ----------------------------------------------------------------------------------------------------------------

  redis:
    image: docker.io/bitnami/redis:6.2
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/bitnami/redis/data

# GRAFANA --------------------------------------------------------------------------------------------------------------

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
    ports:
      - '3000:3000'

# ----------------------------------------------------------------------------------------------------------------------

volumes:
  redis_data:
  nifi_volume:
