version: "2.2"

services:

# FLINK ----------------------------------------------------------------------------------------------------------------

  jobmanager:
    image: flink:latest
    container_name: jobmanager
    ports:
      - "8081:8081" # Web ui port
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./target:/opt/flink/queries/

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        metrics.reporter.grph.factory.class: org.apache.flink.metrics.graphite.GraphiteReporterFactory
        metrics.reporter.grph.host: graphite
        metrics.reporter.grph.port: 2003
        metrics.reporter.grph.protocol: TCP
        metrics.reporter.grph.interval: 60 SECONDS

# NIFI -----------------------------------------------------------------------------------------------------------------

  nifi:
    image: apache/nifi
    container_name: nifi
    ports:
      - '8080:8080' # Web ui port
    volumes:
      - ./nifi:/nifi-conf/
      - nifi_volume:/opt/nifi/nifi-current/conf/

# GRAPHITE -------------------------------------------------------------------------------------------------------------

  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

# INFLUXDB -------------------------------------------------------------------------------------------------------------

  #influxdb:
    #image: bitnami/influxdb:latest
    #container_name: influxdb
    #ports:
      #- '8086:8086'
    #environment:
      #- INFLUXDB_HTTP_AUTH_ENABLED=true
      #- INFLUXDB_ADMIN_USER_PASSWORD=password123
      #- INFLUXDB_ADMIN_USER_TOKEN=admintoken
    #volumes:
      #- influxdb_volume:/bitnami/influxdb

volumes:
  nifi_volume:
  #influxdb_volume:
    #driver: local
