{
 "title": "SABD_2 metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "graphite" }
  ]
 },
 "panels": [
  {
   "title": "n° task managers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "jobmanager.jobmanager.numRegisteredTaskManagers"
    }
   ]
  },
  {
   "title": "n° task slots available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "jobmanager.jobmanager.taskSlotsAvailable"
    }
   ]
  },
  {
   "title": "n° running jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "jobmanager.jobmanager.numRunningJobs"
    }
   ]
  },
  {
   "title": "n° task slots total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "jobmanager.jobmanager.taskSlotsTotal"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.CPU.Load"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.CPU.Time"
    }
   ]
  },
  { "title": "Garbage collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Garbage collector count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.GarbageCollector.PS-MarkSweep.Count"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.GarbageCollector.PS-Scavenge.Count"
    }
   ]
  },
  {
   "title": "Garbage collector time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.GarbageCollector.PS-MarkSweep.Time"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.GarbageCollector.PS-Scavenge.Time"
    }
   ]
  },
  { "title": "Class Loader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Class Loader",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.ClassLoader.ClassesLoaded"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.ClassLoader.ClassesUnloaded"
    }
   ]
  },
  { "title": "Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Threads count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.Threads.Count"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Direct memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Direct.Count"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Direct.MemoryUsed"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Direct.TotalCapacity"
    }
   ]
  },
  {
   "title": "Heap memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Heap.Committed"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Heap.Max"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Heap.Used"
    }
   ]
  },
  {
   "title": "Mapped memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Mapped.Count"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Mapped.MemoryUsed"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Mapped.TotalCapacity"
    }
   ]
  },
  {
   "title": "Metaspace memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Metaspace.Committed"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Metaspace.Max"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.Metaspace.Used"
    }
   ]
  },
  {
   "title": "NonHeap memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.NonHeap.Committed"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.NonHeap.Max"
    },
    {
     "target": "jobmanager.jobmanager.Status.JVM.Memory.NonHeap.Used"
    }
   ]
  }
 ]
}